# service.yaml
# Service to expose Flask app on port 80 
# Uses NodePort for external access
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
